version: '3.8'

services:
  app:
    image: node:20.18.1
    container_name: vinted_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"
    depends_on:
      - mongodb
    networks:
      - vinted-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb_vinted_public
    command: mongod --port 27018
    ports:
      - "127.0.0.1:27018:27018"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - vinted-network

volumes:
  mongodb_data_container:

networks:
  vinted-network:
